"""Compose thesis_results/production/baseline_generators/baseline_report.md from the artifacts."""
import sys, json
sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parents[1] / 'task11_2026-09-21'))
from harness import *
O = RES / 'baseline_generators'
GENS = ['TimeGAN', 'QuantGAN', 'CNN-WGAN-GP', 'GARCH', 'GJR-GARCH']; CTRL = 'CONTROL: shuffled real'
T5 = ['acf_returns_mae', 'acf_absolute_mae', 'acf_squared_mae', 'hurst_diff', 'resid_kurtosis_diff']; FID = ['mean_diff', 'std_diff', 'wasserstein', 'quantile_mse', 'tail_index_diff', 'extreme_events_diff', 'energy_distance']
OV = pd.read_csv(O / 'overall_ranks.csv'); BT = pd.read_csv(O / 'bootstrap_margins.csv'); SP = pd.read_csv(O / 'draw_to_draw_spread.csv'); PM = pd.read_csv(O / 'per_metric_mean_rank_frame_A.csv', index_col=0)
RAW = pd.read_csv(O / 'raw_temporal_metrics_mean_by_entry.csv', index_col=0); MECH = pd.read_csv(O / 'acf_abs_mechanism.csv', index_col=0); PUBM = pd.read_csv(O / 'published_acf_absolute_mae_by_model.csv', index_col=0)
PROV = json.load(open(O / 'baseline_provenance.json')); VER = json.load(open(O / 'verify_no_oracle.json')); VAL = json.load(open(O / 'validation_vs_phase_b.json'))
nm = {CTRL: 'shuffled control', 'iid': 'iid bootstrap (historical simulation)', 'sb_r': 'stationary block bootstrap (Politis–White on returns)', 'sb_abs': 'stationary block bootstrap, long blocks (Politis–White on |returns|)'}
name = lambda e: nm.get(e, e)
f2 = lambda x: f'{x:.2f}'; f3 = lambda x: f'{x:.3f}'
def ov(fr, sc, e, col): return OV[(OV.frame == fr) & (OV.scenario == sc) & (OV.entry == e)][col].iloc[0]
L = []; A = L.append
A('# Baselines without oracle access: does the benchmark tell no dynamics from good dynamics?\n')
A('Comparison entries only. Nothing here enters the published composite, `FIDELITY_COLS`, `TEMPORAL_COLS`, `{market}_metrics.csv`, or any report text. New files only, under `thesis_results/production/baseline_generators/` and `analysis/baselines_2026-09-21/`; run under `phase_b_venv/bin/python`. Stopping at the end: the framing decision is Victor\'s.\n')
A('## Part 1. The baselines\n')
A('- **iid** (historical simulation): for each market, seed and draw, a series of test-block length sampled with replacement from that market\'s training block.\n- **sb_r** (the specified stationary block bootstrap, Politis & Romano 1994): geometric block lengths, circular wrap inside the training block, mean block length from **Politis–White** (`arch.bootstrap.optimal_block_length`, arch 8.0.0) applied to the training returns, floored at 1.\n- **sb_abs** (added, *not* the specified baseline): same resampler, mean block length from Politis–White on |training returns|. The specified choice returns 0.3–5.4, i.e. almost no dependence, so the "modest short-range dependence" case is nearly iid; the volatility-persistence scale is 110–128, and the temporal metrics measure exactly that, so I ran it as a labelled sensitivity.\n')
A('20 draws per market-seed (15 units, 300 series per baseline), draw *k* of seed *s* from `default_rng([s, k, code])`.\n')
A('| market | n_train | target length | Politis–White b: returns / \\|returns\\| / returns² | mean block used: sb_r / sb_abs | empirical mean block, seed 42: sb_r / sb_abs |\n|---|---|---|---|---|---|')
for m in MARKETS:
    r = PROV['markets'][m]; pw = r['politis_white_stationary']; u = r['mean_block_length_used']; e = r['draws']['42']['empirical_mean_block_length']
    A(f"| {m} | {r['n_train']} | {r['target_length']} | {pw['returns']:.2f} / {pw['abs_returns']:.1f} / {pw['squared_returns']:.1f} | {u['sb_r']:.2f} / {u['sb_abs']:.1f} | {e['sb_r']:.2f} / {e['sb_abs']:.1f} |")
A(f"\nWhy these lengths: FTSE\'s Politis–White length on returns is 0.27, which is not a possible mean block length, so it is floored at 1 (iid). For the other markets the length is used as returned. The empirical mean block length of the generated series matches the target for sb_r and is 6–14% below it for the long blocks, which is the truncation of the last block in a series of about 500 observations.\n")
A(f"**No observation after the end of the training block is read.** (i) `gen_baselines.py` opens `data/processed_files/train/<market>_train.parquet` and nothing else with data: from the test file it takes only the row count, from the parquet footer metadata, to set the target length; the validation file is not opened. (ii) The resamplers are `iid_bootstrap(train, n, rng)` and `stationary_bootstrap(train, n, mean_block, rng)`: the training array, a length and a generator are all they receive. (iii) Every generated index is below n_train (largest index used per market: " + ', '.join(f"{m} {v} of {PROV['markets'][m]['n_train']}" for m, v in VER['max_index_used'].items()) + f"). (iv) All {VER['draws_checked']} stored draws were checked: values not found in the training block = {VER['values_outside_training_block']}; regenerating with the recorded seeds reproduces every draw exactly. Provenance: `baseline_provenance.json` (training-block SHA-256 per market).\n")
A('## Part 2. Scoring\n')
A(f"Every entry is scored per draw against the test block through the notebook\'s own `evaluate_multiple_models` → `FinancialMetrics` (same call as Phase B: `max_lag = min(50, n//4)`, the cached legacy AUC null; BLAS threading as in Phase B, because arch\'s GARCH residual-kurtosis fit differs at 1e-5–1e-3 under single-thread BLAS). **Validation:** the five generators\' and the control\'s rows produced by this call equal Phase B\'s stored rows on all {VAL['cells_compared']} numeric cells, max |difference| {VAL['max_abs_difference']:g}. The two baselines (and sb_abs) go through the identical path.\n")
A('Ranking: the five generators (their 20 fresh Phase B draws, draw *k* paired with baseline draw *k*), the shuffled control (the pipeline\'s fixed `default_rng(42)` permutation, the same in every draw) and the baselines compete in **one pool** per unit and draw, `na_option="bottom"`, average ties; composite = ½(fidelity + temporal). **S0** = the published columns (five temporal metrics + `discriminative_auc_dist` + `discriminative_auc_absz`); **S4** = both discriminative columns out. A unit\'s value is the mean over its 20 draws; "overall" is the mean over the 15 units; position = order of the overall composite. **Primary frame A: eight entries** (five generators, control, iid, sb_r). Frames B (sb_abs replaces sb_r), C (all nine) and P (the *published* generator draws and control against each baseline draw) are sensitivities below. Generators in frames A–C are fresh Phase B draws, not the published recorded draws (which cannot be re-scored; the recorded GAN series were never stored).\n')
A('### 2.1 One ranking (frame A, eight entries)\n')
A('| entry | fidelity rank | temporal rank S0 / S4 | composite S0 | composite S4 | position S0 / S4 |\n|---|---|---|---|---|---|')
ents = ['CONTROL: shuffled real', 'CNN-WGAN-GP', 'GJR-GARCH', 'QuantGAN', 'GARCH', 'sb_r', 'iid', 'TimeGAN']
order = sorted(ents, key=lambda e: ov('A', 'S0', e, 'composite'))
for e in order:
    A(f"| {name(e)} | {f3(ov('A','S0',e,'fidelity_rank'))} | {f3(ov('A','S0',e,'temporal_rank'))} / {f3(ov('A','S4',e,'temporal_rank'))} | {f3(ov('A','S0',e,'composite'))} | {f3(ov('A','S4',e,'composite'))} | {int(ov('A','S0',e,'position'))} / {int(ov('A','S4',e,'position'))} |")
A('\nSensitivities (composite S0 / S4, position S0 / S4):\n')
A('| entry | frame B: sb_abs instead of sb_r | frame C: all nine entries | frame P: published generators + control, baseline draw *k* |\n|---|---|---|---|')
for e in ['CONTROL: shuffled real', 'CNN-WGAN-GP', 'GJR-GARCH', 'QuantGAN', 'GARCH', 'TimeGAN', 'iid', 'sb_r', 'sb_abs']:
    cells = []
    for fr in ('B', 'C', 'P'):
        s = OV[(OV.frame == fr) & (OV.entry == e)]
        cells.append('—' if s.empty else f"{f3(s[s.scenario=='S0'].composite.iloc[0])} / {f3(s[s.scenario=='S4'].composite.iloc[0])}; {int(s[s.scenario=='S0'].position.iloc[0])} / {int(s[s.scenario=='S4'].position.iloc[0])} of {int(s.n_entries.iloc[0])}")
    A(f"| {name(e)} | " + ' | '.join(cells) + ' |')
gm_t = {sc: np.mean([ov('A', sc, g, 'temporal_rank') for g in GENS]) for sc in ('S0', 'S4')}; gm_f = np.mean([ov('A', 'S0', g, 'fidelity_rank') for g in GENS])
A(f"\nGenerators\' mean over the five: fidelity {gm_f:.2f}, temporal {gm_t['S0']:.2f} (S0) / {gm_t['S4']:.2f} (S4).\n")
A('### 2.2 Where the control\'s advantage comes from\n')
A('Composite gap = ½ × fidelity gap + ½ × temporal gap (frame A):\n')
A('| comparison | composite gap S0 | of which fidelity | of which temporal | composite gap S4 | of which fidelity | of which temporal |\n|---|---|---|---|---|---|---|')
for b in ('iid', 'sb_r'):
    row = []
    for sc in ('S0', 'S4'):
        d = ov('A', sc, b, 'composite') - ov('A', sc, CTRL, 'composite'); df = .5 * (ov('A', sc, b, 'fidelity_rank') - ov('A', sc, CTRL, 'fidelity_rank')); dt = .5 * (ov('A', sc, b, 'temporal_rank') - ov('A', sc, CTRL, 'temporal_rank')); row += [f3(d), f"{f3(df)} ({100*df/d:.0f}%)", f"{f3(dt)} ({100*dt/d:.0f}%)"]
    A(f"| {name(b)} minus control | " + ' | '.join(row) + ' |')
A('\n### 2.3 Which temporal metrics fail to penalise missing dynamics\n')
A('Mean rank among the eight (frame A, 300 unit-draws; 1 = closest to real). The last column is the mean over the five generators. Raw values are the mean over 15 units × 20 draws.\n')
mets = T5 + ['dist', 'absz']
A('| metric | control | iid | sb_r | generators (mean) | best generator (rank) | control raw | iid raw | sb_r raw | generators raw (min–max) |\n|---|---|---|---|---|---|---|---|---|---|')
for c in mets:
    g = PM.loc[c, GENS]; rr = RAW[c]
    A(f"| {c} | {f2(PM.loc[c, CTRL])} | {f2(PM.loc[c, 'iid'])} | {f2(PM.loc[c, 'sb_r'])} | {f2(PM.loc[c, 'generators_mean'])} | {g.idxmin()} ({f2(g.min())}) | {rr[CTRL]:.4f} | {rr['iid']:.4f} | {rr['sb_r']:.4f} | {rr[GENS].min():.4f}–{rr[GENS].max():.4f} |")
A('\nThe fidelity metrics for the same entries (mean rank; control / iid / sb_r / generators): ' + '; '.join(f"{c} {f2(PM.loc[c, CTRL])} / {f2(PM.loc[c, 'iid'])} / {f2(PM.loc[c, 'sb_r'])} / {f2(PM.loc[c, 'generators_mean'])}" for c in FID) + '.\n')
A('**Does the theory hold?** *acf_returns_mae*: the control is at the noise floor (0.052 — real and shuffled ACFs of about 500 returns are both near zero, so their MAE is sampling noise), yes, but every entry is there (generators 0.053–0.055, iid 0.049; TimeGAN 0.081): the metric has no resolution, and it ranks iid *better* than the control. *hurst_diff*: holds strongly — control 5.90, iid 6.95 (worst), against 2.9–3.7 for GARCH, GJR-GARCH, CNN-WGAN-GP and QuantGAN. *acf_absolute_mae*: holds only weakly — control 0.0730, iid 0.0716, sb_r 0.0706 against GJR-GARCH 0.0707, GARCH 0.0744, QuantGAN 0.0791, TimeGAN 0.1177 and CNN-WGAN-GP 0.0640: only CNN-WGAN-GP is clearly better than no dynamics. *acf_squared_mae*: **does not hold** — the control (0.0570) and iid (0.0544) score *better* than all five generators (0.063–0.100). *resid_kurtosis_diff*: penalises iid and sb_r (6.19, 5.35), **not** the control (3.08, better than every one of the five generators: 3.47–5.62), because the control has the test block\'s exact marginal. So of the five temporal columns only `hurst_diff` (and, for iid, `resid_kurtosis_diff`) reliably penalise missing dynamics; `acf_returns_mae` and `acf_squared_mae` reward it or cannot tell. `dist` and `absz` (S0 only) carry marginal information: the control ranks 3.0 / 3.6 on them, iid 6.1 / 5.4.\n')
A('**The PROJECT_STATE note (control 0.0730 beats QuantGAN 0.0981 and TimeGAN 0.1232 on acf_absolute_mae).** Those three numbers are exactly the means over the 15 published units (control 0.0730, QuantGAN 0.0981, TimeGAN 0.1232; verified from `{market}_metrics.csv`). They are mean effects of a heavy right tail, not typical units: medians are QuantGAN 0.0630 and TimeGAN 0.0798 against the control\'s 0.0760, and the worst units are 0.250 (QuantGAN) and 0.405 (TimeGAN). Published, QuantGAN beats the control in ' + f"{int(((pd.concat([pd.read_csv(RES/m/f'seed{s}'/f'{m}_metrics.csv').assign(u=f'{m}{s}') for m in MARKETS for s in (42,43,44)]).pivot_table(index='u', columns='model', values='acf_absolute_mae')['QuantGAN'] < (pd.concat([pd.read_csv(RES/m/f'seed{s}'/f'{m}_metrics.csv').assign(u=f'{m}{s}') for m in MARKETS for s in (42,43,44)]).pivot_table(index='u', columns='model', values='acf_absolute_mae')[CTRL])).sum()))} of 15 units and TimeGAN in {int(((pd.concat([pd.read_csv(RES/m/f'seed{s}'/f'{m}_metrics.csv').assign(u=f'{m}{s}') for m in MARKETS for s in (42,43,44)]).pivot_table(index='u', columns='model', values='acf_absolute_mae')['TimeGAN'] < (pd.concat([pd.read_csv(RES/m/f'seed{s}'/f'{m}_metrics.csv').assign(u=f'{m}{s}') for m in MARKETS for s in (42,43,44)]).pivot_table(index='u', columns='model', values='acf_absolute_mae')[CTRL])).sum()))}.\n")
A('Does that mean those two generators produce worse volatility clustering than none at all? Partly, and for different reasons. On fresh draws the ACF of |r| over lags 1–50 (real: lag 1 0.159, lag 10 0.081, lag 50 −0.022, mean 0.051) looks like this:\n')
A('| entry | mean ACF(\\|r\\|), lags 1–50 | signed bias vs real | MAE vs real (= acf_absolute_mae) | share of unit-draws with MAE above the control\'s | lag 1 / 10 / 50 (draw 0, mean over units) |\n|---|---|---|---|---|---|')
for e in [CTRL, 'iid', 'sb_r', 'sb_abs'] + GENS:
    r = MECH.loc[e]; A(f"| {name(e) if e in nm else e} | {r.mean_acf_abs_lags_1_50:+.3f} | {r.signed_bias_vs_real_mean:+.3f} | {r.mae_vs_real_mean:.4f} | {100*r.share_units_draws_mae_gt_control:.0f}% | {r.acf_abs_lag1:+.3f} / {r.acf_abs_lag10:+.3f} / {r.acf_abs_lag50:+.3f} |")
A('\nThe no-dynamics entries have a flat ACF near zero, so their error is simply the mean magnitude of the real ACF (about 0.07). **QuantGAN** clusters volatility too strongly and never lets it decay (mean ACF 0.143 against 0.051, lag 50 0.069 against −0.022): its error is a bias, and it is worse than nothing on the unit-draws where that bias is large — but in 58% of draws it beats the control, and its median published unit does. **TimeGAN**\'s mean profile is roughly right (0.065) but erratic from draw to draw, which gives it the largest error (0.118) and a worse-than-control result in 52% of draws. **GARCH** and **GJR-GARCH** are too weak at lag 1 (0.079 / 0.085 against 0.159) and end up level with the control (0.074, 0.071 against 0.073). The larger point is the resolution of the metric: the gap between doing nothing (0.073) and the best generator (CNN-WGAN-GP 0.064) is 0.009, half of CNN-WGAN-GP\'s own draw-to-draw sd within a unit (0.019) and under a third of GARCH\'s (0.031; QuantGAN 0.035, TimeGAN 0.043).\n')
A('## Part 3. Separation from noise\n')
A('Bootstrap: the 15 units resampled with replacement, **B = 19,999**, each entry\'s overall composite recomputed; margin = composite(best generator) − composite(entry), so a **negative margin means the generator is ahead** of the baseline. The best generator is the one with the lowest overall composite in that frame (CNN-WGAN-GP in frames A–C, GJR-GARCH in frame P). "Units + draws" also resamples the 20 draws inside each resampled unit (paired across entries), which carries the baselines\' own generation noise.\n')
A('| frame | scenario | entry | best generator | margin (best gen − entry) | 95% interval, 15 units | excludes zero? | 95% interval, units + draws | excludes zero? |\n|---|---|---|---|---|---|---|---|---|')
for _, r in BT.iterrows():
    A(f"| {r.frame} | {r.scenario} | {name(r.entry)} | {r.best_generator} | {r.margin_best_minus_entry:+.3f} | [{r.ci_lo:+.3f}, {r.ci_hi:+.3f}] | {'**yes**' if r.excludes_zero else 'no'} | [{r.two_level_ci_lo:+.3f}, {r.two_level_ci_hi:+.3f}] | {'**yes**' if r.two_level_excludes_zero else 'no'} |")
A('\n**Draw-to-draw spread** (frame A and the sb_abs frame; the overall composite of the entry in each of the 20 draws, then its spread across draws; the control is one fixed permutation, so its spread comes only from the generators it is ranked against):\n')
A('| frame | scenario | entry | overall composite: mean (sd over draws) | range over draws | mean within-unit sd | position over the 20 draws: min – mode – max | draws ahead of every generator |\n|---|---|---|---|---|---|---|---|')
for _, r in SP.iterrows():
    A(f"| {r.frame} | {r.scenario} | {name(r.entry)} | {r.overall_composite_mean:.3f} ({r.overall_composite_sd_over_draws:.3f}) | {r['min']:.3f}–{r['max']:.3f} | {r.within_unit_sd_mean:.3f} | {int(r.position_min)} – {int(r.position_mode)} – {int(r.position_max)} | {int(r.draws_ahead_of_all_generators)} of 20 |")
A('\n## Part 4. Summary\n')
A('| entry | fidelity rank | temporal rank (S0 / S4) | composite S0 | composite S4 | position among eight (S0 / S4) |\n|---|---|---|---|---|---|')
for e in order:
    A(f"| {name(e)} | {f3(ov('A','S0',e,'fidelity_rank'))} | {f3(ov('A','S0',e,'temporal_rank'))} / {f3(ov('A','S4',e,'temporal_rank'))} | {f3(ov('A','S0',e,'composite'))} | {f3(ov('A','S4',e,'composite'))} | {int(ov('A','S0',e,'position'))} / {int(ov('A','S4',e,'position'))} |")
a = {sc: {e: ov('A', sc, e, 'composite') for e in ents} for sc in ('S0', 'S4')}
A('\n### Which explanation the evidence supports\n')
A(f"**Both, unequally: the oracle marginal is the dominant cause of the control\'s composite win, strongly supported; the weak temporal penalty is real but partial and metric-specific.**\n")
A(f"1. **Oracle marginal — strong.** The control wins (composite {a['S0'][CTRL]:.2f} S0 / {a['S4'][CTRL]:.2f} S4 against {a['S0']['CNN-WGAN-GP']:.2f} / {a['S4']['CNN-WGAN-GP']:.2f} for the best generator), and it wins on fidelity: fidelity rank {ov('A','S0',CTRL,'fidelity_rank'):.2f}. The two baselines that have no oracle access and no dynamics-fitting do **not** win: iid is seventh of eight in both scenarios (composite {a['S0']['iid']:.2f} / {a['S4']['iid']:.2f}), sb_r sixth ({a['S0']['sb_r']:.2f} / {a['S4']['sb_r']:.2f}), and neither is ahead of every generator in a single one of the 20 draws. The generators are ahead of iid by {abs(BT[(BT.frame=='A')&(BT.scenario=='S0')&(BT.entry=='iid')].margin_best_minus_entry.iloc[0]):.2f} composite points (95% interval excludes zero; the same holds against the published generators, in S4, and with draws resampled). The fidelity family accounts for {100*.5*(ov('A','S0','iid','fidelity_rank')-ov('A','S0',CTRL,'fidelity_rank'))/(ov('A','S0','iid','composite')-ov('A','S0',CTRL,'composite')):.0f}% of the composite gap between the control and iid under S0 and {100*.5*(ov('A','S4','iid','fidelity_rank')-ov('A','S4',CTRL,'fidelity_rank'))/(ov('A','S4','iid','composite')-ov('A','S4',CTRL,'composite')):.0f}% under S4 (table 2.2). So the control\'s win is what an exact test-block marginal buys, which is a legitimate reason to keep it out of the competition.")
A(f"2. **Weak temporal penalty — partial.** The temporal family alone ranks the control {ov('A','S0',CTRL,'temporal_rank'):.2f} (S0) / {ov('A','S4',CTRL,'temporal_rank'):.2f} (S4) of eight against the generators\' mean {gm_t['S0']:.2f} / {gm_t['S4']:.2f}: at their mean or slightly better, as before. That is not all oracle: with no oracle, iid ranks {ov('A','S0','iid','temporal_rank'):.2f} / {ov('A','S4','iid','temporal_rank'):.2f} (worse than the generators\' mean by 0.7 / 0.4 places, better than TimeGAN), and sb_r {ov('A','S0','sb_r','temporal_rank'):.2f} / {ov('A','S4','sb_r','temporal_rank'):.2f} — level with the generators\' mean. The long-block sb_abs, a pure resample of training history, is at {ov('B','S0','sb_abs','temporal_rank'):.2f} / {ov('B','S4','sb_abs','temporal_rank'):.2f} against {ov('B','S0','GARCH','temporal_rank'):.2f} / {ov('B','S4','GARCH','temporal_rank'):.2f} for GARCH and {ov('B','S0','QuantGAN','temporal_rank'):.2f} / {ov('B','S4','QuantGAN','temporal_rank'):.2f} for QuantGAN; it is fifth of eight under S0 and fourth under S4, level with GARCH and QuantGAN, and behind CNN-WGAN-GP by {abs(BT[(BT.frame=='B')&(BT.scenario=='S0')&(BT.entry=='sb_abs')].margin_best_minus_entry.iloc[0]):.2f} composite points (interval excludes zero). By metric (2.3): `hurst_diff` penalises missing dynamics strongly; `acf_absolute_mae` only weakly (the gap to no dynamics is half the best generator\'s own draw-to-draw sd); `acf_returns_mae`, `acf_squared_mae` and, for the control, `resid_kurtosis_diff` do not penalise it or reward it.")
A('3. **What the evidence does not support.** The strongest form of the concern — that the benchmark cannot tell no dynamics from good dynamics — is not supported at the composite level for a fair no-dynamics baseline: iid and sb_r rank sixth and seventh, and the separation from the best generator is outside the bootstrap noise. What it does support is narrower: the temporal family carries little information about dynamics per se (control and sb_r at the generators\' mean; three of five columns unable to separate), so the composite\'s ordering among the *generators* leans on the fidelity family and on `hurst_diff`; and GARCH and QuantGAN are not distinguishable from a block bootstrap of the training data with blocks of about 120 observations (frame B, S0: composite 4.68 and 4.64 against 4.66 for sb_abs; margin sb_abs − GARCH −0.02 [−0.17, +0.12], sb_abs − QuantGAN +0.02 [−0.15, +0.18]; S4 likewise, all four intervals contain zero; `extra_checks.json`).')
A('\nCaveats: generators in the pool are fresh Phase B draws (frame P repeats the comparison with the published generator rows and reaches the same reading, with GJR-GARCH as the best generator); fidelity ranks of the baselines are penalised by the shift between training-block and test-block marginals, which the oracle control does not suffer and the trained generators partly share; the baselines are compared on the same 15 units, whose seeds of one market share the same real data.\n')
A('Stopping here. The framing decision is Victor\'s.\n')
(O / 'baseline_report.md').write_text('\n'.join(L)); print('written', len('\n'.join(L)), 'chars')
