"""Compose thesis_results/production/scenario_matrix/scenario_matrix_report.md from the CSV/JSON artifacts (tables are computed, prose is fixed text)."""
import sys, json
sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent))
from harness import *
MODELS = ['TimeGAN', 'QuantGAN', 'CNN-WGAN-GP', 'GARCH', 'GJR-GARCH']; CTRL = 'CONTROL: shuffled real'
S = pd.read_csv(OUT / 'scenario_summary.csv'); CH = pd.read_csv(OUT / 'rank_changes_vs_published.csv'); SD = pd.read_csv(OUT / 'seed_spread.csv'); CT = pd.read_csv(OUT / 'control_composite.csv')
NF = pd.read_csv(OUT / 'noise_floor_position_changes.csv'); dd = json.load(open(OUT / 'noise_floor_draw_to_draw.json')); WIN = pd.read_csv(OUT / 'winner_counts_by_draw.csv', index_col=0)
NUL = pd.read_csv(OUT / 'part1_nulls_by_scheme.csv'); COST = pd.read_csv(OUT / 'part1_embargo_cost.csv'); NIF = pd.read_csv(OUT / 'part1_nifty50_sub_0_5.csv'); OB = pd.read_csv(OUT / 'part1_observed_auc_by_scheme.csv')
WF = pd.read_csv(OUT / 'part1_observed_walk_forward_contiguous.csv'); CR = pd.read_csv(OUT / 'control_metric_ranks_published.csv', index_col=0); CRF = pd.read_csv(OUT / 'control_metric_ranks_fresh.csv', index_col=0)
CP = pd.read_csv(OUT / 'control_permutation_auc.csv'); V = pd.read_csv(OUT / 'validation_S0_vs_published.csv')
f3 = lambda x: f'{x:.3f}'; f4 = lambda x: f'{x:.4f}'; pc = lambda x: f'{100*x:.1f}%'
tag = {('P', 'S0'): 'S0 published', ('P', 'S1'): 'S1 (published draw)'}
def label(r): return tag.get((r.frame, r.scenario), r.scenario + ' (fresh draws)')
L = []
A = L.append
A('# Task 11: purged and embargoed CV, and the scenario matrix — report and stop\n')
A('Measurement only. No metric definition in the live path, no TEMPORAL_COLS, no composite, no report text was changed. One code change, an option: `FinancialMetrics.compute_discriminative_score(cv="contiguous"|"purged", embargo=None)` and the matching pass-through in `compute_auc_null`, notebook cell 16. The default is the published behaviour, bit for bit (checked below). Everything ran under `phase_b_venv/bin/python`. Scripts: `analysis/task11_2026-09-21/`; artifacts: `thesis_results/production/scenario_matrix/`.\n')
A('## 0. Constraints applied, and two limits you should read first\n')
A('- **No test-period null was attempted** (0 positions at the evaluation length inside the test block, 1 with validation). The null is the approved **full-series fixed-length adjacent sliding null**, computed exhaustively at both evaluation lengths (Track A: L = test block, 486–501; walk-forward: L = N//6 = 810–832). **Stated limitation: its population spans 20 years, while the observed comparison is the test period.** Nothing was done to engineer around it. It carries about 5 independent block pairs at Track A length and 3 at walk-forward length; positions overlap almost entirely.')
A('- **The published GAN draws cannot be re-scored.** The series behind the recorded metrics of TimeGAN, QuantGAN and CNN-WGAN-GP were never stored (Part 4 of the overnight report: the `.npz` holds a second `generate()` call), so a purged AUC of the published GAN draws does not exist and cannot be computed without retraining. Two frames follow. **Frame P (published draw)** has S0 and S1 only, exact, from `{market}_metrics.csv`. **Frame F (fresh draws)** has all six scenarios: for each of the 20 Phase B draws per market-seed the metrics and both AUCs come from that same draw, the per-draw composite is computed, and a unit\'s composite is the mean over the 20 draws. Between F rows only the scenario differs. Frame F is therefore the only place the scenarios are comparable with each other; frame P is the anchor to what was published.')
A(f'- Ranks are the pipeline\'s (five generators, `na_option="bottom"`, average ties). The control does not compete in the published ranks; where its composite is reported it is re-ranked as a **sixth competitor** (6-pool), which changes the generators\' values slightly, so those are reported separately.\n')
A('## Part 1. Purged and embargoed cross-validation\n')
A('### 1.1 The option and what it costs\n')
A('Folds stay contiguous: the test chunks are scikit-learn\'s own stratified, unshuffled chunks (one contiguous chunk per class per fold). For each class block, training rows within the embargo of the test chunk are dropped on both sides. **Embargo = `AUC_WINDOW` = 20 rows** (a window covers 20 observations, so any embargo ≥ 19 leaves no observation shared between a training row and a test row; measured minimum index gap 21). Shuffled folds are not offered by the option: they leak through the window overlap.\n')
c = COST[COST.length == 'track_a']; w = COST[COST.length == 'walk_forward']
A(f'Cost per fold, 5 folds (rows of the stacked real|synthetic training design, both classes): **40, 80, 80, 80, 40 rows dropped**. Track A (L = {c.L.min()}–{c.L.max()}, {c.windows_per_class.min()}–{c.windows_per_class.max()} windows per class): {c.pct_dropped_min.min():.1f}–{c.pct_dropped_min.max():.1f}% of the training rows in the two edge folds, {c.pct_dropped_max.min():.1f}–{c.pct_dropped_max.max():.1f}% in the three interior folds; smallest training set {c.min_train_rows.min()} rows. Walk-forward (L = {w.L.min()}–{w.L.max()}): {w.pct_dropped_min.min():.1f}–{w.pct_dropped_max.max():.1f}%; smallest training set {w.min_train_rows.min()} rows. **The folds are not too small to fit** at either length (the option raises if one ever is, and it did not). It does become infeasible for short comparisons: on the test-block pairs `[0:n]` vs `[n:2n]` used for the numbers you quoted, purged CV cannot be fitted for n < 83.\n')
A('Verification: (i) default path bit-identical to the pre-change notebook on 18 real/synthetic pairs and in `compute_auc_null`; (ii) `purged(embargo=0)` equals `contiguous` exactly; (iii) `shuffled` is refused; (iv) `verify_notebook.py` exits 0; (v) Phase B rerun for all 15 market-seeds with the changed notebook equals the earlier Phase B (before the option) on all 66,600 numeric cells, max |difference| 0; (vi) the contiguous sliding nulls reproduce Task 10\'s on all 36,320 positions (max |difference| 1.1e-16) and the contiguous observed AUCs reproduce Phase B\'s own `discriminative_auc_raw` (1.1e-16, 1,800 series).\n')
A('### 1.2 NIFTY50 first: is the anti-predictive mass leakage-adjacent or drift?\n')
A('| construction | draws with contiguous AUC < 0.5 | mean, contiguous | mean, shuffled folds | **mean, purged** | share > 0.5, shuffled | share > 0.5, purged |\n|---|---|---|---|---|---|---|')
for _, r in NIF.iterrows():
    if r.construction.startswith('full-series'): A(f"| {r.construction} | {int(r.n_sub_0_5_contiguous)} of {int(r.n_positions)} ({pc(r.share_sub_0_5)}) | {f3(r.mean_contiguous)} | {f3(r.mean_shuffled)} | **{f3(r.mean_purged)}** | {pc(r.share_above_0_5_shuffled)} | {pc(r.share_above_0_5_purged)} |")
r = NIF.iloc[2]; r2 = NIF.iloc[3]
A(f"| test-block pairs `[0:n]` vs `[n:2n]` (the 0.300 / 0.665 / 94% numbers), all {int(r.n_sub_0_5_contiguous)} draws; purged fits {int(r.purged_feasible)} of them | {int(r.n_sub_0_5_contiguous)} | {f3(r.mean_contiguous)} | {f3(r.mean_shuffled)} | not defined for {int(r.n_sub_0_5_contiguous - r.purged_feasible)} draws (n < {int(r2.min_n_feasible)}) | {pc(r.share_above_0_5_shuffled)} | — |")
A(f"| same, the {int(r2.n_sub_0_5_contiguous)} draws where purged CV fits | {int(r2.n_sub_0_5_contiguous)} | {f3(r2.mean_contiguous)} | {f3(r2.mean_shuffled)} | **{f3(r2.mean_purged)}** | {pc(r2.share_above_0_5_shuffled)} | {pc(r2.share_above_0_5_purged)} |\n")
A('**Result: it stays near the contiguous value. The drift is real and the metric is measuring it.** Purged folds leave the anti-predictive draws where they were (0.380 → 0.358 at Track A, 0.355 → 0.326 at walk-forward; on the quoted test-block pairs, 0.403 → 0.195 on the draws where it fits) and only 1.0% / 0.3% of them cross 0.5, against 98.8% / 90.1% under shuffled folds. The share of the whole null below 0.5 goes **up** under purging (NIFTY50 Track A 20.9% → 25.6%). The shuffled-fold values near 0.62–0.67 are what leakage through overlapping windows produces, not what a corrected estimator recovers. I proceeded, as both outcomes were results.\n')
A('### 1.3 All five markets: the null, at both evaluation lengths\n')
A('Full-series sliding null (approved construction), exhaustive. Mean, sd, p97.5 and the share of draws below 0.5, under contiguous (published), purged (embargo 20) and shuffled (diagnostic only, leaks) folds, on the same pairs. Independent block pairs ≈ N/2L (5.0 at Track A, 3.0 at walk-forward).\n')
A('| market | length (L, positions) | scheme | mean | sd | p97.5 | share < 0.5 |\n|---|---|---|---|---|---|---|')
for m in MARKETS:
    for tg in ('track_a', 'walk_forward'):
        for sc in ('contiguous', 'purged', 'shuffled'):
            r = NUL[(NUL.market == m) & (NUL.length == tg) & (NUL.scheme == sc) & (NUL.null == 'full-series sliding')].iloc[0]
            A(f"| {m} | {'Track A' if tg == 'track_a' else 'walk-forward'} ({int(r.L)}, {int(r.n)}) | {sc} | {f3(r['mean'])} | {f3(r.sd)} | {f3(r.p97_5)} | {pc(r.frac_lt_0_5)} |")
A('\nThe stationary GARCH-t reference (Task 10 recipe: 300 pairs of independent stationary paths from the seed-42 fit; SHANGHAI is the constrained boundary fit, 8 / 5 pairs rejected by the generation guard) under the same schemes:\n')
A('| market | length | contiguous: mean (sd) | purged: mean (sd) | shuffled: mean (sd) | share < 0.5: contiguous / purged / shuffled |\n|---|---|---|---|---|---|')
for m in MARKETS:
    for tg in ('track_a', 'walk_forward'):
        g = {sc: NUL[(NUL.market == m) & (NUL.length == tg) & (NUL.scheme == sc) & (NUL.null == 'stationary GARCH-t')].iloc[0] for sc in ('contiguous', 'purged', 'shuffled')}
        A(f"| {m} | {'Track A' if tg == 'track_a' else 'walk-forward'} | {f3(g['contiguous']['mean'])} ({f3(g['contiguous'].sd)}) | {f3(g['purged']['mean'])} ({f3(g['purged'].sd)}) | {f3(g['shuffled']['mean'])} ({f3(g['shuffled'].sd)}) | {pc(g['contiguous'].frac_lt_0_5)} / {pc(g['purged'].frac_lt_0_5)} / {pc(g['shuffled'].frac_lt_0_5)} |")
A('\nReading: on a stationary process the purged null centres on 0.50 (0.50–0.55; SHANGHAI 0.63–0.69 on the boundary fit), contiguous folds sit 0.01–0.03 higher, and shuffled folds sit at 0.63–0.71 (SHANGHAI 0.75–0.80) — the leak. On the real series the purged null is 0.52–0.68: the excess over the stationary reference is regime drift, and it is present at both lengths.\n')
A('### 1.4 The observed discriminative AUC under each scheme\n')
A('Track A length. The published GAN series are unavailable, so the observed values are the means over the 20 fresh Phase B draws × 3 seeds (60 series per cell; the contiguous value reproduces Phase B\'s own `discriminative_auc_raw` to 1.1e-16). The control is the pipeline\'s fixed `default_rng(42)` permutation, as published.\n')
g = OB[OB.model != CTRL]
A('| model | mean over 5 markets: contiguous | purged | shuffled (diag.) |\n|---|---|---|---|')
for mod in MODELS + [CTRL]:
    o = OB[OB.model == mod]; A(f"| {mod} | {f3(o.auc_contiguous.mean())} | {f3(o.auc_purged.mean())} | {f3(o.auc_shuffled.mean())} |")
A(f"\n**Market-model cells (25) above the same-scheme null:** contiguous {int(g.above_p97_5_contiguous.sum())}/25 above p97.5 and {int(g.above_mean_1_96sd_contiguous.sum())}/25 above mean + 1.96 sd; **purged {int(g.above_p97_5_purged.sum())}/25 and {int(g.above_mean_1_96sd_purged.sum())}/25**; shuffled {int(g.above_p97_5_shuffled.sum())}/25 and {int(g.above_mean_1_96sd_shuffled.sum())}/25. Walk-forward length, published contiguous AUCs (mean over folds and seeds; purged and shuffled cannot be recomputed because the fold series of the walk-forward generators were not stored): {int(WF.above_p97_5.sum())}/25 above p97.5, {int(WF.above_mean_1_96sd.sum())}/25 above mean + 1.96 sd. **Your zero-of-25 statement holds under purged CV as well.**")
A('\nThe control\'s AUC by market (contiguous / purged): ' + '; '.join(f"{m} {OB[(OB.market == m) & (OB.model == CTRL)].auc_contiguous.iloc[0]:.2f} / {OB[(OB.market == m) & (OB.model == CTRL)].auc_purged.iloc[0]:.2f}" for m in MARKETS) + f". Over 20 further random permutations of each market\'s test block (sensitivity, not used in the scenarios) the purged AUC is {CP[CP.perm_seed != 42].auc_purged.mean():.3f} on average with sd {CP[CP.perm_seed != 42].auc_purged.std():.3f}, range {CP[CP.perm_seed != 42].auc_purged.min():.2f}–{CP[CP.perm_seed != 42].auc_purged.max():.2f}; contiguous {CP[CP.perm_seed != 42].auc_contiguous.mean():.3f}. A discriminator that worked would put a series with no dynamics well above the real-versus-real null. Under both time-blocked schemes the control sits **below** the real-versus-real null in four of the five markets (null means 0.56–0.69) and **above** it in FTSE (0.70 / 0.68 against 0.59 / 0.57): its value is decided by which way the market drifts, not by the missing dynamics.\n")
A('**Limitation recorded:** the sliding nulls above are populations of adjacent 20-year-series blocks, the observed comparison is the test period, and the block pairs overlap almost entirely (≈5 and ≈3 independent pairs). Residual, not changed: the `StandardScaler` in the metric is fit on all rows before the folds are cut, so scaling statistics from the test chunk enter the training features under every scheme, purged included.\n')
A('## Part 2. The scenario matrix\n')
A('| # | null | CV | ranked discriminative columns |\n|---|---|---|---|\n| S0 | legacy (n_rep = 20) | contiguous | dist + absz (published) |\n| S1 | length-matched sliding | contiguous | dist + absz |\n| S2 | length-matched sliding | purged | dist + absz |\n| S3 | length-matched sliding | purged | dist only |\n| S4 | — | purged | neither (both to DESCRIPTIVE_COLS) |\n| S5 | stationary GARCH-t reference | purged | dist + absz |\n')
A(f'**Validation.** Recomputing fidelity, temporal and composite ranks from the raw metric columns under S0 reproduces the published values for all 75 model-evaluations: max |difference| {V.d_fid.max():.1e} (fidelity), {V.d_tmp.max():.1e} (temporal), {V.d_comp.max():.1e} (composite) — last-bit rounding of the mean — and every per-metric rank and every within-unit position identical. The same recomputation on each Phase B draw equals Phase B\'s own composite_rank ({8.9e-16:.1e}). For S1 the published-draw result reproduces Task 10: CNN-WGAN-GP 2.548 first, GJR-GARCH 2.567 second, margin 0.019.\n')
A('Composite (overall = mean over the 15 units; lower is better), position in brackets, and the margin between first and second:\n')
A('| frame | scenario | ' + ' | '.join(MODELS) + ' | first | second | margin |\n|---|---|' + '---|' * (len(MODELS) + 3))
for _, r in S.iterrows():
    A(f"| {r.frame} | {label(r)} | " + ' | '.join(f"{r[f'composite_{m}']:.4f} ({int(r[f'position_{m}'])})" for m in MODELS) + f" | {r['first']} | {r.second} | {r.margin:.4f} |")
A('\n**How many of the 75 model-evaluations change rank relative to the published result.** "Position" = the model\'s 1–5 position inside its unit; "composite value" = the unit composite differs from the published one. Frame F compares a draw-averaged unit composite with a single published draw, so it carries draw noise as well as the scenario; the last columns separate the two.\n')
A('| frame | scenario | position changed (of 75) | composite value changed (of 75) | mean abs composite change | units with any position change (of 15) | vs F-S0, same units: positions / values | one fresh draw at a time: position changes vs published, mean (range) | same draw, scenario vs S0: mean (range) |\n|---|---|---|---|---|---|---|---|---|')
for _, r in CH.iterrows():
    nf = NF[NF.scenario == r.scenario].iloc[0] if r.frame == 'F' else None
    A(f"| {r.frame} | {r.scenario} | {int(r.position_changed_vs_published)} | {int(r.composite_value_changed_vs_published)} | {r.mean_abs_composite_change:.3f} | {int(r.units_with_any_position_change)} | " + (f"{int(r.position_changed_vs_F_S0)} / {int(r.composite_value_changed_vs_F_S0)}" if r.frame == 'F' else '—') + ' | ' + (f"{nf.single_draw_position_changes_vs_published_mean:.1f} ({int(nf['min'])}–{int(nf['max'])})" if nf is not None else '—') + ' | ' + (f"{nf.same_draw_position_changes_vs_S0_mean:.1f} ({int(nf.same_draw_min)}–{int(nf.same_draw_max)})" if nf is not None else '—') + ' |')
A(f"\n**The noise floor is the finding here.** Two different fresh draws of the *same* scenario (S0) put {dd['draw_to_draw_S0_mean']:.0f} of the 75 model-evaluations in a different within-unit position (range {dd['draw_to_draw_S0_min']}–{dd['draw_to_draw_S0_max']}); a fresh draw against the published result: 52–53. Replacing S0 by S1, S2, S3, S5 on the *same* draw moves 6, 10, 13 and 10 positions, and S4 moves 23. Every scenario effect on positions is between a tenth and a half of the draw-to-draw noise floor.\n")
A('### The shuffled control through every scenario\n')
A('Control re-ranked as a sixth competitor. "Beats best" = the control\'s composite is below the best generator\'s in the same 6-pool.\n')
A('| frame | scenario | control fidelity rank | control temporal rank (generators\' mean) | **control composite** | best generator | its composite | control beats best: units of 15 | draws of 300 |\n|---|---|---|---|---|---|---|---|---|')
for _, r in CT.iterrows():
    A(f"| {r.frame} | {label(r)} | {r.control_fidelity_rank_6pool:.3f} | {r.control_temporal_rank_6pool:.2f} ({r.generators_temporal_rank_6pool:.2f}) | **{r.control_composite_6pool:.3f}** | {r.best_generator} | {r.best_generator_composite_6pool:.3f} | {int(r.units_control_beats_best_generator)} | " + (f"{100*r.draw_level_share_control_beats_best_generator:.0f}%" if r.frame == 'F' else '—') + ' |')
A('\n**Does demoting the discriminative columns let the control back into contention? No — it was never out of it, in any scenario, published included.** With the control competing, its composite is 2.16–2.33 against 3.23–3.40 for the best generator; it beats the best generator in 13 of 15 units under S0 as published and in 15 of 15 in every fresh-draw scenario. It does so because it scores 1.0 on six of the seven fidelity metrics by construction (fidelity rank 1.03) and the composite gives that family half the weight. Its temporal rank, the part the composite is meant to police it with, is 3.3–3.6 of 6 in every scenario, the same as the generators\' average (3.5): the temporal family does not rank the shuffled series below a typical generator in S0 either. S4 moves the control from 2.16 to 2.26 (fresh draws), and the share of draws in which it beats the best generator falls from 91% (S0) to 70% (S4) — no gain for the control. So the test you set does not count against S4; what it shows is that the composite offers no protection against the control in any scenario, and that excluding the control from the ranks by construction (as the pipeline does) is what keeps it from winning, in S0 as in S4.\n')
A('Control rank on each ranked metric (6-pool, mean over 15 units; 1 = closest to real): ' + ', '.join(f"{k} {v:.2f}" for k, v in CR.iloc[:, 0].items() if k in ('acf_returns_mae', 'acf_absolute_mae', 'acf_squared_mae', 'hurst_diff', 'resid_kurtosis_diff', 'dist', 'absz')) + '. On fresh draws the length-matched columns give dist_contiguous ' + f"{CRF.loc['dist_c'].iloc[0]:.2f}, dist_purged {CRF.loc['dist_p'].iloc[0]:.2f}, absz_length-matched contiguous {CRF.loc['absz_lm_c'].iloc[0]:.2f}, purged {CRF.loc['absz_lm_p'].iloc[0]:.2f}. Only hurst_diff and acf_absolute_mae rank the control near the bottom; the discriminative columns place it mid-pack (dist) or worse (absz, because a two-sided z-score flags an AUC of 0.43 against a null of 0.6).\n")
A('## Part 3. Is the margin real?\n')
A('Bootstrap: the 15 market-seed units resampled with replacement, **B = 19,999**, each model\'s overall composite recomputed (mean over the resampled units), margin = composite(second) − composite(first) for the first and second of the point estimate, 95% percentile interval. "P(reversed)" is the share of resamples in which the order of the two is reversed or tied. Sensitivity, labelled as an addition: resampling the 5 markets (all 3 seeds of each), because seeds of one market share the real data.\n')
A('| frame | scenario | first | second | margin | 95% interval (15 units) | excludes zero? | P(reversed) | P(first stays first) | 95% interval (5 markets) | excludes zero? |\n|---|---|---|---|---|---|---|---|---|---|---|')
for _, r in S.iterrows():
    A(f"| {r.frame} | {label(r)} | {r['first']} | {r.second} | {r.margin:.4f} | [{r.ci_lo:+.3f}, {r.ci_hi:+.3f}] | {'**yes**' if r.excludes_zero else 'no'} | {100*r.p_order_reversed:.0f}% | {100*r.p_first_stays_first:.0f}% | [{r.cluster_ci_lo:+.3f}, {r.cluster_ci_hi:+.3f}] | {'**yes**' if r.cluster_excludes_zero else 'no'} |")
A(f"\n**No scenario\'s 95% interval on the first-versus-second margin excludes zero** — not the published S0, not any length-matched, purged or stationary-reference variant, in either frame, and not under the market-level resampling. First and second are not separable by this benchmark. That is the answer, not a failure to find a winner. Two further readings of the same fact: across the 20 fresh draws, scored one draw at a time, the overall winner is CNN-WGAN-GP in {int(WIN.loc['S0', 'CNN-WGAN-GP'])}, GJR-GARCH in {int(WIN.loc['S0', 'GJR-GARCH'])}, GARCH in {int(WIN.loc['S0', 'GARCH'])} of 20 under S0, and the split is the same in every scenario (CNN-WGAN-GP {int(WIN['CNN-WGAN-GP'].min())}–{int(WIN['CNN-WGAN-GP'].max())}, GJR-GARCH {int(WIN['GJR-GARCH'].min())}–{int(WIN['GJR-GARCH'].max())}); and in the published draw the GJR-GARCH lead comes from one seed (margins by seed 42/43/44: {SD[(SD.frame == 'P') & (SD.scenario == 'S0') & SD.model.str.startswith('MARGIN')].margins_by_seed.iloc[0]}; under S1: {SD[(SD.frame == 'P') & (SD.scenario == 'S1') & SD.model.str.startswith('MARGIN')].margins_by_seed.iloc[0]}).\n")
A('The two frames bracket the noise: frame P intervals (about ±0.45) contain the single-draw noise of the published run, frame F intervals (about ±0.13) come from draw-averaged composites and contain almost none of it. Neither excludes zero.\n')
A('**Seed-to-seed spread.** Standard deviation of a model\'s unit composite over the 3 seeds inside a market (ddof = 1), averaged over the 5 markets (largest single market in brackets):\n')
A('| frame | scenario | ' + ' | '.join(MODELS) + ' | second − first margin, sd over seeds (values by seed) |\n|---|---|' + '---|' * (len(MODELS) + 1))
for (fr, sc), g in SD.groupby(['frame', 'scenario'], sort=False):
    r = ' | '.join(f"{g[g.model == m].seed_sd_mean_over_markets.iloc[0]:.3f} ({g[g.model == m].seed_sd_max_over_markets.iloc[0]:.2f})" for m in MODELS); mg = g[g.model.str.startswith('MARGIN')].iloc[0]
    A(f"| {fr} | {sc} | {r} | {mg.seed_sd_mean_over_markets:.3f} ({mg.margins_by_seed}) |")
A('\nPublished draw: 0.56–0.84 per model (the composite of a model in one market moves by more than half a rank place between seeds), which is larger than the 0.08 published margin. Fresh draws remove the draw component and leave the training-run component: 0.10–0.48. In frame F the sign of the margin is the same in all three seeds under S2 and S5 (CNN-WGAN-GP ahead by 0.03–0.09), and differs by seed under S0, S1, S3 and S4.\n')
A('## Part 4. Summary\n')
A('| scenario | first | second | margin | 95% bootstrap interval on the margin (15 units) | excludes zero? | control\'s composite (6-pool) |\n|---|---|---|---|---|---|---|')
for _, r in S.iterrows():
    cr = CT[(CT.frame == r.frame) & (CT.scenario == r.scenario)].iloc[0]
    A(f"| {label(r)} | {r['first']} | {r.second} | {r.margin:.4f} | [{r.ci_lo:+.3f}, {r.ci_hi:+.3f}] | {'**yes**' if r.excludes_zero else 'no'} | {cr.control_composite_6pool:.3f} (best generator {cr.best_generator_composite_6pool:.3f}) |")
A('\nRows marked "published draw" use the published series (S0, S1 only). Rows marked "fresh draws" use 20 Phase B draws per market-seed and are the only ones in which S2–S5 exist.\n')
A('### Recommendation (the decision is Victor\'s)\n')
A('**Recommend S4: move `discriminative_auc_dist` and `discriminative_auc_absz` to DESCRIPTIVE_COLS, with purged CV as the way any AUC that is still reported is computed.** Reasoning, in the order the evidence came:\n')
A('1. **The choice among scenarios does not decide who is first.** No interval excludes zero in any of the eight rows; the overall winner flips with the draw in about 40% of fresh draws in every scenario. Whatever is chosen, the honest statement is that GJR-GARCH and CNN-WGAN-GP are not separable here. The scenario effects on positions (6–23 of 75 on the same draw) are small next to the draw-to-draw floor (53 of 75).')
A('2. **Purged CV is the right estimator but does not repair the metric.** On a stationary reference it recovers a null centred on 0.50 (contiguous is 0.01–0.03 high, shuffled 0.63–0.71 from leakage), so it removes the boundary leak. On the real series the anti-predictive draws stay (NIFTY50 0.380 → 0.358) because they are regime drift, and the purged null is broad (sd 0.14–0.19, p97.5 0.81–0.98). Against it 0 of 25 market-model cells rise above p97.5 or mean + 1.96 sd, under purged exactly as under contiguous, at Track A length; the same 0 of 25 at walk-forward length (contiguous only).')
A('3. **Neither ranked column has a working reference under any scheme I tested.** `dist` measures distance from 0.5 where the real-versus-real level is 0.52–0.68; the shuffled control scores 0.43 purged (0.31–0.68 across markets; below the null in four markets, above it in FTSE) and is rated mid-pack. `absz` (S1, S2, S5) is a z-score against a null of 3 to 5 independent blocks that mixes 20 years of regimes, and its choice is the thing that moved first and second in Task 10. Retaining them (S1, S2, S5) changes the ranking by no more than the noise; retaining `dist` alone (S3) keeps the flaw you identified.')
A('4. **S4 does not help the control.** With the control competing, its composite is 2.16 (S0) and 2.26 (S4) and its temporal rank is 3.3 and 3.5 against the generators\' 3.5 either way. The composite does not police the control in any scenario, S0 included; the exclusion of the control from the ranks is doing that work, and S4 does not change it. Should you prefer a scenario that keeps an AUC column, **S2 is the cleanest retention** (purged, length-matched); S5, with the stationary reference null, gives the same ranking within the noise.')
A('5. **Costs of S4, stated plainly.** The temporal family shrinks to five metrics (three ACF errors, Hurst, GARCH-residual kurtosis) against seven fidelity metrics, each temporal column now carrying 1/10 of the composite instead of 1/14; it moves 23 of 75 within-unit positions on the same draw against S0, the most of any scenario; its first-second margin is the smallest (0.010); and the benchmark loses its only supervised real-versus-synthetic test. That test is not doing measurable work as built: it does not place any generator outside real-versus-real, and it does not detect the control.')
A('\nNot done, by instruction or by construction: no test-period null; no change to `FIDELITY_COLS`, `TEMPORAL_COLS`, the composite, `{market}_metrics.csv`, `generate_report.py`, `report_data.py` or any report text; no retraining; Phase A untouched. New tracked-file change: `3_4_integrated_pipeline.ipynb` (the purged option; default unchanged). New untracked outputs are under `analysis/task11_2026-09-21/`, `thesis_results/production/scenario_matrix/`, and `thesis_results/production/*/seed*/phase_b_COMMIT_DRIFT/` for the twelve market-seeds that did not yet have one. Stopping here.\n')
(OUT / 'scenario_matrix_report.md').write_text('\n'.join(L)); print('written', OUT / 'scenario_matrix_report.md', len('\n'.join(L)), 'chars')
